sudo: false
language: python
dist: xenial
python:
- '3.6'
- '3.7'
deploy:
  provider: pypi
  skip_existing: true
  user: brndnmtthws
  password:
    secure: UJT6SWq6s8rXSZKlKHMalqF8HaXuAadJ2GGVVj8qSSYgnKF8MejgeLXXGYDsLC4DZv5uTrLsjvVUBSI0eDd7sL/6sYXD5mO3ceZLV01yjEt6wQYfD/uty21jCEpicLzmGTtx3lZV7t/lk4B911ExRm3zVBg5jP3tz+IIWOxoK1gtOcFLnwHfggIcdvEJUFvs1hLm1KOEzDGfpYPIwRt3zkRz/tsf/EfHUVJvecCoG0K1C92SXNYv17pL3a/73Jbj5dyonvkIAzlWRsanBPKUeh0F4chw80onFqz8D3qbPF+vUBMIcvrheWhBunVP3KqyUyi3Ln5T6gMh9yORDpn+g1gS8ypSuyasFtLa1YLSuSK9YAmYhrMZez6ihy7lr8IFp4pj8Px0TxjC1Cf19JeH6yaHwPkc2HNjufyyYUz9KLnT7VI7uHcqCMpA6Wpj4sxJihD7aASMVZIRGfXpHESCoOdYCyxnEx++IQHGolGg7rdlBRtGSSc/LdIntvtZkc7GwSxMZ6HbMjoP3VEKdBmZoj8/GT4vgBXdc6y1qRHslpi0f7oeA+ILM6gMgIw89SA08AQbInDppTFjQlyvVph5ae55nZAzi0vefoGM5kXtW+Kf9jeYPyXz/dfthNpweg+c8TghNxjoS0ZizKB5ecDZM0sPjHP43gUX4K+K+L0GlEk=
  on:
    tags: true
env:
  global:
  - CC_TEST_REPORTER_ID=c374ef9c1b0a01c90e2f60d4aef23be79e48692486706dce16e14e65c1d22b15
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- py.test --cov=dragon_rest --cov-report xml
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
cache: pip
